apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLables:
     app: db
  template:
   metadata: 
     labels: 
      app: db
  spec:
    conatainers:
      - iamge: postgres:15-alpine
        name: postgres
        env: 
         - name: POSTGRES_USER
           valueFrom: 
            configMapKeyRef:
             name: config
             key: POSTGRES_USER
         - name: POSTGRES_PASSWORD
           valueFrom:
             secretKeyRef:
              name: secret
              key: POSTGRES_PASSWORD
        ports:
         - containerPort: 5432
           name: postgres
        volumeMount:
         - mountPath: /var/lib/postgressql/data
           name: db-data
        volumes:
         - name: db-data
           emptyDir: {}
           
  